### ISSUE TITLE
Pay, Point, Wish, Ott UI

### ISSUE THREAD

**Issue by wxxd-fxrest** [wxxd-fxrest/WOODLIX#21]
## 작업 내용
Pay, Point, Wish, UI, 데이터 연결

### to-do

- [ ]  결제 관리에 대한 데이터 저장
- [ ]  Point 결제 및 충전, 예매 취소 시 환불 기능
- [ ]  Wish 데이터 저장 및 바인딩
- [ ]  구매 OTT 상세페이지 이동 (Cell click -> Detail Page)
- [ ]  이전 예매 티켓 UI
